### ISSUE TITLE
[Router] Shorter refs?

### ISSUE THREAD

**Issue by Shikkic** [gophr-pm/gophr#160]
It would probably be better to have shortened refs if possible. Future optimization maybe? ` b5232bb`...

**Comment by skeswa** [comment]
Why is this in QA fam?

**Comment by Shikkic** [comment]
I thought you had a PR for it in the router? I might have been mistaken.

**Comment by skeswa** [comment]
Nurp. That was for fully qualified SHAs. Starting this one presently. The mini-SHAs are only going to work for refs of branches, tags, PRs and heads btw.

**Comment by skeswa** [comment]
Put this on hold while writing tests for the router and depot.
