### ISSUE TITLE
Determine package download numbers

### ISSUE THREAD

**Issue by Shikkic** [gophr-pm/gophr#69]
Popular
Trending
(New, eventually?)

**Comment by skeswa** [comment]
Okay, so this is a whole body of work:
- [ ] We need a table for the all-time download numbers for packages
- [ ] We need a table for day-range download numbers (so a counter for all days within a range)
- [ ] We need a table for storing the all-time download numbers on specific package versions
- [ ] We need a table for storing the day-range download numbers on specific package versions

**Comment by Shikkic** [comment]
What do you mean by table? Keyspace?

**Comment by Shikkic** [comment]
Also for reference this ties in issues number #47 #48 and #49

**Comment by skeswa** [comment]
**All-time Package Download Numbers**
```sql
CREATE TABLE gophr.package_download_totals (
  package_author TEXT,
  package_repo TEXT,
  downloads COUNTER,
  PRIMARY KEY ((package_author, package_repo), downloads)
) WITH CLUSTERING ORDER BY (downloads DESC);
```

**Comment by Shikkic** [comment]
Do cassandra not have FK? Curious if we would want to look up the download stats in relation to a package. But it's non-relational so I'm not sure if that concept makes sense

**Comment by skeswa** [comment]
Nope. No such thing as a FK. CQL is mostly an illusion. The underlying implementation for cassandra is a distributed key-value store.

**Comment by skeswa** [comment]
Pivoted away from sorting logic being performed by cassandra. Writing a new microservice called turnstile for this. The branch is called `feature/turnstile`.

**Comment by Shikkic** [comment]
Interesting, will take a look

**Comment by Shikkic** [comment]
PR?

**Comment by Shikkic** [comment]
Needs to be tested at scale

**Comment by Shikkic** [comment]
This was finished right? We implemented turnstile. So we can close this right?

**Comment by skeswa** [comment]
Your next task as writing a job that turns daily downloads into weekly, monthly and all-time.

**Comment by Shikkic** [comment]
I know, just doing house keeping on old issues.
